Code/skyrim_ui/package-lock.json
Code/skyrim_ui/src/app/components/server-list/server-list.component.ts

> The geolocation code relies on a thirdparty service that rate limits requests, this is a temporary work around as it fails listing servers because there are too many. ~yamashi

disable geolocation in the serverlist for now

---

README.md

Note that personally I am not sure that it is worth to keep a separate repository just for bugs, however, as long as it is the case it is important to make it visible.

Add reference to bug report repository in Readme

---

Code/client/Services/Generic/InputService.cpp

this allows you to exit UI in Linux using Proton

feat: add escape to UI

---

Code/client/Games/Skyrim/TESObjectREFR.cpp

This seems to be mostly a singleplayer fix, but it might work for other things too, gotta test.

Fix enchant crash

---

.gitignore
Code/client/Services/Generic/TransportService.cpp
Code/encoding/Messages/AuthenticationResponse.h
Code/server/GameServer.cpp
Code/skyrim_ui/src/app/components/connect/connect.component.html
Code/skyrim_ui/src/app/components/connect/connect.component.ts
Code/skyrim_ui/src/app/components/error/error.component.html
Code/skyrim_ui/src/app/components/error/error.component.ts
Code/skyrim_ui/src/app/components/group/group.component.html
Code/skyrim_ui/src/app/components/group/group.component.scss
Code/skyrim_ui/src/app/components/group/group.component.ts
Code/skyrim_ui/src/app/components/order/order.component.html
Code/skyrim_ui/src/app/components/order/order.component.ts
Code/skyrim_ui/src/app/components/root/root.component.html
Code/skyrim_ui/src/app/components/root/root.component.ts
Code/skyrim_ui/src/app/components/server-list/server-list.component.html
Code/skyrim_ui/src/app/components/server-list/server-list.component.ts
Code/skyrim_ui/src/app/components/settings/settings.component.html
Code/skyrim_ui/src/app/components/settings/settings.component.scss
Code/skyrim_ui/src/app/components/settings/settings.component.ts
Code/skyrim_ui/src/app/services/client.service.ts
Code/skyrim_ui/src/app/services/error.service.ts
Code/skyrim_ui/src/app/services/group.service.ts
Code/skyrim_ui/src/app/services/setting.service.ts
Code/skyrim_ui/src/assets/i18n/en.json
Code/skyrim_ui/src/index.html
Code/skyrim_ui/src/styles.scss
Code/skyrim_ui/src/typings.d.ts

- allow group UI to be repositioned
- show meaningful errors when connect fails
- improve server list sorting UI

UI improvements

---

Code/skyrim_ui/README.md

Fixes https://github.com/tiltedphoques/TiltedEvolution/issues/358

Linking the UI build guide in the wiki

---

Code/client/Services/Generic/InputService.cpp

Changed the key down 'hack' to key up. Seems to work excellent on both Linux and Windows. Cleaned up the code a bit.

tweak: input method changes to allow linux

---

Code/skyrim_ui/src/app/services/error.service.ts
Code/skyrim_ui/src/assets/i18n/en.json

"Server full" message in UI

---

Code/client/Systems/AnimationSystem.h

Seems I put the Type instead of the actual variable name.

Actually Fixed Comment

---

README.md

add build badge linux in the readme

---

Code/server/Services/CalendarService.cpp

Fix incorrect bounds for hours and minutes

---

Code/skyrim_ui/src/app/app.module.ts
Code/skyrim_ui/src/app/components/checkbox/checkbox.component.ts
Code/skyrim_ui/src/app/components/dropdown/dropdown.component.ts
Code/skyrim_ui/src/app/components/settings/settings.component.ts
Code/skyrim_ui/src/app/directives/radio.directive.ts
Code/skyrim_ui/src/app/directives/slider.directive.ts

Currently some input elements make sounds when they are changed and some don't. This PR standardises sounds for checkboxes, radio buttons, dropdown menus and sliders so they all make the correct sounds when changed.

Fix and standardize sounds for input elements

---

Code/components/console/CommandSettingsProvider.cpp
Code/components/console/CommandSettingsProvider.h
Code/server/main.cpp
Code/server_runner/DediRunner.cpp
Code/server_runner/DediRunner.h

The goal is to not need the .ini file in managed environments

feat: can now set all options from command line

---

Code/skyrim_ui/src/assets/i18n/zh-CN.json

Update translation  to dev branch

Update Chinese Simplified i18n file

---

Code/client/Games/Skyrim/Magic/EffectItem.cpp
Code/client/Games/Skyrim/Magic/EffectItem.h
Code/client/Games/Skyrim/Magic/MagicTarget.cpp
Code/client/Games/Skyrim/Magic/MagicTarget.h

Activating night vision on one client triggered it on the other.
Issue #585

fix: nightvision effect syncing

---

Code/client/Events/RemoveWaypointEvent.h
Code/client/Events/SetWaypointEvent.h
Code/client/Games/Skyrim/PlayerCharacter.cpp
Code/client/Games/Skyrim/PlayerCharacter.h
Code/client/Services/Generic/MapService.cpp
Code/client/Services/MapService.h
Code/client/World.cpp
Code/encoding/Messages/ClientMessageFactory.h
Code/encoding/Messages/NotifyRemoveWaypoint.cpp
Code/encoding/Messages/NotifyRemoveWaypoint.h
Code/encoding/Messages/NotifySetWaypoint.cpp
Code/encoding/Messages/NotifySetWaypoint.h
Code/encoding/Messages/RequestRemoveWaypoint.cpp
Code/encoding/Messages/RequestRemoveWaypoint.h
Code/encoding/Messages/RequestSetWaypoint.cpp
Code/encoding/Messages/RequestSetWaypoint.h
Code/encoding/Messages/ServerMessageFactory.h
Code/encoding/Opcodes.h
Code/server/Services/MapService.cpp
Code/server/Services/MapService.h
Code/server/World.cpp

Waypoints (those blue map markers) are synced within a party now.

Sync waypoints

---

Code/immersive_launcher/stubs/FileMapping.cpp

…and STR mods are loaded
Under MO2, there's a bug caused when calling RealGetModuleFileNameW on XAudio2_7.dll, it crashes in usvfs. This only happens during the game shutdown paths when the last few threads are exiting. This PR just avoids that bug.
TODO: Further analysis of what is under MO2 USVFS and what is needed.

Fix game exit crash when under ModOrganizer2, when only Address Library

---

Code/skyrim_ui/src/assets/i18n/tr.json

Resend (Accidentally sent it to master branch)

Turkish Translation.

---

Code/skyrim_ui/src/app/transloco-root.module.ts
Code/skyrim_ui/src/assets/i18n/ja.json

- Added full JA translation including the two newly added warning messages.
Thank you to Miredirex for the guidance on how to publish this.

(JA Support) Added Ja.JSON and updated transloco-root.module.ts to include Japanese

---

Code/skyrim_ui/src/app/transloco-root.module.ts
Code/skyrim_ui/src/assets/i18n/no.json

Adds the Norwegian translations from my [Nexus Mod](https://www.nexusmods.com/skyrimspecialedition/mods/69993) and added new sentences.

Norwegian Translation

---

Code/server/Services/QuestService.cpp

Addressing synchronization issues during the initialization phase of partial sub-tasks.

fix quest start

---

xmake.lua

This should version pin all present packages and their dependencies

tweak: Version pinning

---

Code/client/main.cpp

Address library updated the names for each specified version

Update Address Library mod name in error popup

---

Code/client/Services/Generic/MagicService.cpp
Code/client/Services/Generic/OverlayClient.cpp
Code/client/Services/MagicService.h
Code/client/Services/OverlayClient.h
Code/client/World.h
Code/skyrim_ui/src/app/components/root/root.component.html
Code/skyrim_ui/src/app/components/root/root.component.scss
Code/skyrim_ui/src/app/components/root/root.component.ts
Code/skyrim_ui/src/app/mock/skyrimtogether.mock.ts
Code/skyrim_ui/src/app/services/client.service.ts
Code/skyrim_ui/src/assets/i18n/de.json
Code/skyrim_ui/src/assets/i18n/en.json
Code/skyrim_ui/src/assets/i18n/es.json
Code/skyrim_ui/src/assets/i18n/fr.json
Code/skyrim_ui/src/assets/i18n/pl.json
Code/skyrim_ui/src/assets/i18n/ru.json
Code/skyrim_ui/src/assets/i18n/tr.json
Code/skyrim_ui/src/styles.scss
Code/skyrim_ui/src/typings.d.ts
Code/tp_process/ProcessHandler.cpp

https://github.com/user-attachments/assets/45c4e86f-89fe-44f0-8233-ee7715ca95c8

Made the 'Reveal Players' feature more user-friendly

---

.github/workflows/playable-build.yml

Will run every Friday at 1:00 p.m. UTC

Set up automated CI for outputting weekly builds

---

Code/client/CrashHandler.cpp
Code/client/TiltedOnlineApp.h

Fixes build issue with PR #705 
With @miredirex.

Make exception handling PR 705 fully compatible with IS_MASTER

---

README.md

Someone  noticed a dangling Fallout 4 reference, so here's the removal PR.

Remove Fallout  4 reference.

---

Code/client/Games/Misc/Lock.h
Code/client/Games/Skyrim/TESObjectREFR.cpp
Code/client/Services/Generic/ObjectService.cpp

Fix lock state synchronization

Fix lock state synchronization

---

Code/server/Services/CharacterService.cpp

Ensure proper sync of modified faction data

Fix faction data sync issue
