- Code/client/Services/Generic/MagicService.cpp
Related to issue #225 . Healing hands is a concentration spell, which were all cancelled through magic effect sync. This should in theory fix it. Has to be tested still, but if it doesn't work, these changes are harmless, so it can be merged.
> Fix healing hands not working

- Code/client/Games/Skyrim/Actor.cpp
- Code/client/Games/Skyrim/Actor.h
This should get closer to the problem. This code bypasses the queued kill that seems to happen whenever a killcam is involved, and just forcefully kills the actor. Needs to be tested, will do with the internal test team.
> Potential fix for actors not dying

- Code/client/Games/Skyrim/TESObjectREFR.cpp
- Code/client/Games/Skyrim/TESObjectREFR.h
When dropping a duped quest item, and the party leader joined your cell again, the SetInventory() function would re-add the quest item. This PR contains a check that only adds a quest item if that person were present to receive it at the time of the party leader looting it.
> Quest item re-appearing in inventory after dropping it

- README.md
Link was broken to the badge, fixed it for the windows workflow. Possibly might want to display a different badge (or add one) such as the build status of something else or the number of issues, forks, etc...
> Fixed workflow status badge

- Code/client/Games/Skyrim/Interface/UI.cpp
Can't take credit for this fix, pretty much entirely taken from Skyrim Soulse RE: https://github.com/Vermunds/SkyrimSoulsRE/blob/master/src/Menus/FavoritesMenuEx.cpp#L42
> Fix for hotkeys in favorites menu not working

- Code/client/Games/Skyrim/Forms/TESNPC.h
- Code/client/Services/Debug/DebugService.cpp
- Code/client/Services/Generic/CharacterService.cpp
- Code/client/Services/Generic/PartyService.cpp
- Code/client/Services/Generic/PlayerService.cpp
Random encounters that were previously invisible, should now be visible. They also won't duplicate. You must be in a party to get random encounters. The client of the party leader spawns the encounters in. Some random encounters might still occasionally have differences in the type of npc, like seeing an orc woman instead of a human man, or a skeever instead of a wolf. Regardless, they should at least spawn now.
> Sync random encounters

- Code/client/Services/Generic/ActorValueService.cpp
This should fix the issue where enemies had way too much loot on their bodies, like a dragon having 300 dragon bones. The Kill() function was called every time the health decreased below 0, which it keeps doing even when it dies. When Kill() is called, it generates loot. This was especially noticeable with spells like Flames, where there were a lot of damage decreases. Should fix #233 .
> Fix: duplicated loot

- Code/client/Services/Generic/ObjectService.cpp
- Code/encoding/Structs/ServerSettings.cpp
- Code/encoding/Structs/ServerSettings.h
- Code/server/GameServer.cpp
For most players, leaving player home sync disabled is fine. However, some players might prefer to have their home base synced for various reasons. 
This adds a new config variable, `bSyncPlayerHomes`, defaulting to `false`, which toggles whether player homes are synced.
Legacy of the Dragonborn is one such example - it has it's own player home, but contains functionality that depends on the contents of several chests within the home. As such, a player might want to re-enable sync if they want to play with it.
This fixes #308!
> Add config option for player home / NoCellReset sync

- Code/client/Services/Generic/OverlayService.cpp
This is an actual fix for the overflowing of health in the health bar.
This fixes the overflow of health on the health bar caused by temporary boosts to health
> Fix: Health Overflow Proper

- Code/components/es_loader/ESLoader.cpp
Should allow for mod policy to be usable on Linux when using loadorder.txt generated on Windows.
> fix: line endings on loadorder.txt

- Code/client/Services/Generic/OverlayService.cpp
- Code/skyrim_ui/src/app/services/client.service.ts
- Code/skyrim_ui/src/assets/i18n/en.json
Currently the Client sends a system message with  "successfully connnected/disconnected" whenever you connect to or disconnect from a server. These strings are hardcoded in the Client and cannot be translated. Displaying information should left to the UI, not the client.  This also makes it easy for the UI to later change how the messages should look, such as using a popup notification.
> Let UI handle connect/disconnect messages

- Code/client/Games/Misc/BSScript.cpp
Other players in the area should now not transform when one player transforms into a werewolf or vampire lord. Certain things may break now, like the dragon claw door, but it is a relatively small trade off, and this door script should be modified through SkyrimTogether.esp anyway.
> Fix beastform

- Code/skyrim_ui/src/app/components/chat/chat.component.ts
- Code/skyrim_ui/src/app/components/chat/message-history.ts
Use the up and down arrows to scroll through your sent chat messages/commands so you can easily repeat them. Inspired by the functionality in CMD and BASH.
example:
- type in and send message "/tp player"
- hit the up arrow key and enter to send the same command again.
Needs cleaning before it's merged, but I'd like to check in if anyone is working on something similar or for comments before spending too much time on it.
> Scroll through sent chat messages with the arrow keys

- Code/client/ScriptExtender.cpp
SKSE and F4SE has diffrent method names for starting them. This adds an #if to choose the correct one based on which version you are building.
> Let FT start F4SE

- Code/server/GameServer.cpp
An often requested feature.
~~Submitted as draft becuase `aStack.Pop<uint16_t>()` currently throws with `std::bad_any_cast` regardless of which numeric types I use. Everything else works as expected, so any help on this would be appreciated.~~
EDIT:
Solved with the help of cosideci
> Server command for setting ingame time

- Code/server/GameServer.cpp
- Code/server/GameServer.h
This prevents users from setting server names that are extremely long and announcing them to the Serverlist. 
Limit is set to 100 bytes. Server names over this will result in the name being truncated and an error message in the console.
Tested on STServer and FTServer.
> Truncate Server name when it's loaded from config

- Code/client/Games/Misc/BSScript.cpp
Script extender stuff isn't implemented for fallout together yet, caused build to fail.
> Fix fallout together build

- .github/workflows/docker-builder.yml
- .github/workflows/docker.yml
- Dockerfile
- Dockerfile.builder
This adds automatic docker image build using Github actions based on git events.
- all images are OCI compliants
- all images are multi arch (amd64 and arm64 for now, pretty much any arch can be added through QEMU)
- images can still be built independently of the GA environment with basic docker commands
This simplify the release/testing process and now we are not reliant anymore on anyone available time and hardware 😉  
The builder base image is now the official [gcc:12.1.0](https://hub.docker.com/_/gcc) image, it contains the setup of cmake/xmake. The build can be run manually through Github action panel, and pushes a single multi arch `latest` image (see [example here](https://hub.docker.com/r/a1ex4/st-builder/tags), [build logs …
> CI: Add automatic docker builds

- Code/server/GameServer.cpp
- Code/server/GameServer.h
- Code/server/Services/CalendarService.cpp
- Code/server/Services/CalendarService.h
Let you set how fast time passes on the server. 
- 0 will stop the clock
- 1 will move at realtime
- 1000 set it to 50x skyrim's normal speed
Tested in game with two clients. Left on for an hour at 1000 timescale with no noticable effects, other than water moving animating way too fast.
https://user-images.githubusercontent.com/43607012/181633426-df0830c2-1ecd-42a8-8d2e-427f227efd37.mp4
> Add TimeScale Server Setting

- Code/server_runner/DediRunner.cpp
Runs `SaveSettingsToIni` right after the GameServer has been initialized. All previous settings are kept and missing ones will be populated with defaults. Fixes #445.
> Regenerate server ini on startup

- Code/skyrim_ui/src/assets/i18n/de.json
- Code/skyrim_ui/src/assets/i18n/nl.json
Just noticed SERVICE.PLAYER_LIST.PARTY_INVITE was missing in both languages.
Great if @RobbeBryssinck and @scomans could check the NL and DE translations respectively.
> Add missing German and Dutch translation strings for party invite

- Code/skyrim_ui/src/app/components/notification-popup-container/notification-popup-container.component.scss
- Code/skyrim_ui/src/app/components/notification-popup-container/notification-popup-container.component.ts
- Code/skyrim_ui/src/app/components/notification-popup/notification-popup.component.html
- Code/skyrim_ui/src/app/components/notification-popup/notification-popup.component.scss
- Code/skyrim_ui/src/app/components/notification-popup/notification-popup.component.ts
- Code/skyrim_ui/src/app/models/popup-notification.ts
- Code/skyrim_ui/src/app/services/mock-client.service.ts
- Code/skyrim_ui/src/app/services/player-list.service.ts
- Code/skyrim_ui/src/app/services/popup-notification.service.ts
- Code/skyrim_ui/src/assets/i18n/de.json
- Code/skyrim_ui/src/assets/i18n/en.json
As the title says, you can now accept party invites by pressing the "Accept" button on the notification, where previously it only brough up the party menu. "Decline" button is not included as this is not implemented in the client. Notification will disappear after 30s or if you click on it.
I have reworked popup notifcations so they support images, icons and buttons with callbacks. They also scale propely based on their contents.
German translation are included to test translations. Not a native speaker, so feel free to correct my grammar.
> Accept party invite from popup notification

- Code/server/GameServer.cpp
Refactored code to be a bit more readable and consistent.  Changed /TogglePvp and /TogglePremium commands to be true toggles, no boolean argument necessary.  Added feedback after command was successfully executed to inform user of state of toggled setting.
~~Initially I was going to add /SetPvp and /SetPremium for explicit setting of commands, but seemed unnecessary/redundant.  Left the code in but commented out, welcome to enable or delete as preferred.~~
> Minor tweak to Server Settings (TogglePvp and TogglePremium)

- Code/server/GameServer.cpp
- Code/server/Services/ServerListService.cpp
Fix for a bug where uServerPort and uMaxPlayerCount would neither load from or save to config file.
> Fix bug in server settings config load/save

- Code/server_runner/main.cpp
`linux` did not seem to be defined and thus the RegisterQuitHandler for linux did not compile at all.  Tests were passed even though the function CtrlHandler was incorrectly typed -- `bool (*)(int)` when __sighandler_t is `void (*)(int)`.
This fixes both the compile by switching to `__linux__` and incorrect typedef.  Since CtrlHandler is now void instead of bool the logic for attempting to save our dear life has been removed.
Tested in Ubuntu 22.04 with gcc-12.
> Fix for RegisterQuitHandler under linux

- Code/server/Services/PartyService.cpp
OnPartyChangeLeader and OnPartyKick does not check if the recieved playerid is actually valid, which can cause a server crash due to the target Player being a nullptr. 
This adds checks to both methods to prevent these crashes.
> Fix vulnerabilites in PartyService

- Code/client/Games/Fallout4/Actor.h
- Code/client/Games/References.cpp
- Code/client/Games/Skyrim/Actor.cpp
- Code/client/Games/Skyrim/Actor.h
- Code/client/Services/Generic/DiscoveryService.cpp
- Code/client/Services/Generic/PlayerService.cpp
- Code/client/Services/PlayerService.h
- Code/encoding/Structs/ServerSettings.cpp
- Code/encoding/Structs/ServerSettings.h
- Code/server/GameServer.cpp
The multiplayer death system is now an optional, default enabled server setting, since some people want to use an alternative death system through other mods. Disabling our death system includes a fat warning on server startup, since this can cause issues.
> Optional death system

- Code/skyrim_ui/src/app/components/connect/connect.component.html
- Code/skyrim_ui/src/app/components/connect/connect.component.scss
- Code/skyrim_ui/src/app/components/root/root.component.ts
- Code/skyrim_ui/src/app/components/server-list/server-list.component.html
- Code/skyrim_ui/src/app/components/server-list/server-list.component.scss
- Code/skyrim_ui/src/app/components/server-list/server-list.component.ts
- Code/skyrim_ui/src/app/components/settings/settings.component.ts
- Code/skyrim_ui/src/app/services/setting.service.ts
- Code/skyrim_ui/src/styles.scss
- Save password is now readable and has proper margins
- Input boxes light up when hovered or focused, so you can see where you are typing even if the caret doesn't load
- Server list no longer skips around when scrolling. This was solved by making the font size fixed again so it doesn't interfere virtual scroll.
Before:
After:
> Connect dialog styling fixes

- Code/client/Services/Generic/InputService.cpp
'q' was being detected as a toggle key when the KEYEVENT_CHAR event was propagated.
> fix: q key not working in chat

- Code/client/main.cpp
Clarifies the required Address Library version and adds a button that links to the Address Library troubleshooting page on the wiki
> tweak: addlib error clarification

- Code/client/Games/Misc/SubtitleManager.cpp
Fixed issue #406  for me.
Tested with chicken and fox.
> fix: crash when attempting soul trap animal #406

- Dockerfile
- Dockerfile.builder
- docker-compose.yml
- docker-multiarch-build.sh
In an effort to teach myself a bit more about Docker, I set about reconfiguring the docker build process for the server.
I matched the docker build process a bit more closely to the `Build linux` workflow, just in case there are any build differences that don't catch edge-case issues.  This includes using `ubuntu:22.04` as a base, installing gcc-12/g++-12 with apt and using `apt update-alternatives` to set it as default.
I also used a little bit of intermediate build trickery to copy only the architecture specific libstdc++.so.6, though I placed it in the server directory (instead of system lib directory) to get around platform issues.
Added `docker-multiarch-build.sh` which automates the build process, including pushing to docker hub.  The commands for building manually are contained in …
> Tweak for multi-stage, multi-arch build for docker server

- Code/client/Games/Skyrim/Forms/TESObjectCELL.h
reproduction:
-load game
-coc whiterun 
-provoke nearest guard and get killed
-game crash during respawn
fix tested on dev branch + fix: animations with new skyrim update
fixed issue for me, but I am not sure that my change doesn't break anything else.
> fix: respawn crash

- Code/client/Games/Skyrim/BSAnimationGraphManager.h
Bethesda has modified another struct, BSAnimationGraphManager. Needed extra padding to properly work again, so that NPCs can draw their weapons and the player can sprint.
> fix: animations with new skyrim update

- Code/encoding/Structs/ReferenceUpdate.cpp
- Code/server/Services/ServerListService.cpp
Exception shouldn't really be thrown in the event of too many requests to the client.
> fix: serverlist related crashes

- Code/client/CrashHandler.cpp
- Code/client/Services/Debug/DebugService.cpp
Fix for #538 
This fix contains log flush, when CrashHandler is used.
I don't know how fix it, when ScopedCrashHandler is used, but this should not be problem, because PR #511 (Crash dump dialog) remove ScopedCrashHandler and use CrashHandler for master and dev branches.
> fix: force spdlog flush on crash

- Code/client/Games/Fallout4/Sky/Sky.h
- Code/client/Games/References.cpp
- Code/client/Games/Skyrim/Sky/Sky.h
- Code/client/Services/Generic/WeatherService.cpp
- Code/client/Services/WeatherService.h
The old weather code had some problems. Skyrim's weather update loop didn't like being cancelled, resulting in crashes and odd visual bugs. This new strategy does not hook or cancel anything, but will instead use native functions ForceWeather and ReleaseWeatherOverride to force usage of the party leader's weather. In case that fails, there's a polling fallback.
> Weather code rework

- Code/immersive_launcher/xmake.lua
Fix issue with command:
xmake install -o distrib
error: install failed, cannot copy file table: 000001D37A5633A0\..\bin, file not found!
> fix: error in xmake install -o distrib

- Code/client/CrashHandler.cpp
- Code/client/Services/Generic/CharacterService.cpp
- Code/client/Services/Generic/InputService.cpp
- Code/client/Services/Generic/InventoryService.cpp
- Code/client/Services/Generic/OverlayClient.cpp
- Code/client/TiltedOnlineApp.cpp
- Code/client/TiltedOnlinePCH.h
Fix for #234.
Tested mainly with Czech keyboard, that contains characters that were also broken (ěšěčšřčžřýáíé...).
Done little testing with Russian keyboard and look to me fixed.
> Fix chat encoding

- Code/client/Games/Skyrim/Misc/BSScript.cpp
This PR fix crash caused when Keyhole for Emerald claw is activated (#561 #568).
NOTE: Issue with door opening synchronizations should be fixed in #570 .
> fix: emerald claw crash

- Code/server/GameServer.cpp
ArgStack integer arguments cannot be popped with any other type than int64_t, as that's how the argstack is created, and std::any will throw if you try to cast it to any other type.
https://github.com/tiltedphoques/TiltedEvolution/blob/master/Code/components/console/ConsoleRegistry.cpp#L290
> fix: SetTime crash

- Code/client/Games/Combat/CombatController.cpp
- Code/client/Games/Combat/CombatController.h
- Code/client/Games/Fallout4/Actor.h
- Code/client/Games/References.cpp
- Code/client/Games/Skyrim/Actor.h
- Code/client/Services/Debug/DebugService.cpp
- Code/client/Services/Generic/CombatService.cpp
Enemies will lock onto players directly without shortly leaving combat first (i.e. sheathing and drawing their weapons constantly).
> Less janky combat targeting

- Code/client/Services/Generic/InventoryService.cpp
Fixed a bug where sometimes, enemies would not have a weapon equipped "internally", meaning that the damage would be whatever damage their unarmed attacks did.
Issue #306
> fix: wrong damage on hit from enemies

- Code/client/Games/Skyrim/TESObjectREFR.cpp
Books now remain in a cell after only reading them
> Fix - Exclude book activation sync when reading them

- Code/client/Games/Memory.cpp
- Code/client/Games/Misc/QuestCallbackManager.cpp
- Tools/Scripts/match_codebase_with_idb.py
Apparently, the id we used for deallocations was the "Reallocate" id. We use the game's internal memory manager sparsely, so this could not have caused any major memory leaks, but a fix is still in order. The PR also includes a small script that matches idb names with codebase names for functions. This can be used to eyeball whether there are any other glaring mismatches. So far, I found one potential mismatch in quest code, which could be investigated.
> Fix: Memory::Free id

- Code/client/Systems/ModSystem.cpp
The lite mod id was assigned to the base ID of the form. The effects of this fix are two-fold: ESL mods will now properly sync, and DJ will stop bothering me about the issue.
> Fix ESL mods not syncing properly

- Code/client/Games/Skyrim/Combat/CombatController.cpp
Loops through target selectors, but upper index must be subtracted by 1.
> Fix: combat crash

- Code/client/Services/Generic/CombatService.cpp
Crash related to projectiles, where parent cells were not transferred properly. Seems to happen only with dragons.
> Fix: dragon crash

- Code/client/xmake.lua
- Code/server/xmake.lua
- xmake.lua
Builds shouldn't break. Version pinning prevents that. Upgrading packages should be a conscious effort, not default behavior.
> Version pinning

- Code/client/TiltedOnlineApp.h
Since we're not really using Sentry crash logs anyway, might as well disable it.
> Disable sentry

- Code/client/Games/Fallout4/TESObjectREFR.cpp
- Code/client/Games/Fallout4/TESObjectREFR.h
- Code/client/Games/Skyrim/TESObjectREFR.cpp
- Code/client/Games/Skyrim/TESObjectREFR.h
This probably worked in the past since there is no reason for the compiler to trash the rax register before returning after the hook, but still, better to have it properly defined.
> Fix Activate() signature

- Code/client/Games/Skyrim/Actor.cpp
- Code/client/Games/Skyrim/Actor.h
- Code/client/Games/Skyrim/ExtraData/ExtraContainerChanges.cpp
- Code/client/Games/Skyrim/ExtraData/ExtraContainerChanges.h
- Code/client/Games/Skyrim/Forms/BGSOutfit.h
- Code/client/Games/Skyrim/Forms/TESForm.h
- Code/client/Games/Skyrim/Forms/TESLevItem.h
- Code/client/Games/Skyrim/Forms/TESLeveledList.h
- Code/client/Games/Skyrim/Forms/TESObjectARMO.h
- Code/client/Games/Skyrim/TESObjectREFR.h
- Code/client/Services/Debug/DebugService.cpp
- Code/client/Services/Generic/InventoryService.cpp
- Code/client/Services/InventoryService.h
Check whether an NPC that should be wearing clothes is naked. What NPCs should be wearing clothes is determined by whether they have a default outfit. This distinguishes NPCs in a city from, say, a falmer.
> Fix naked NPCs bug

- Code/tests/encoding.cpp
Simple fix for array-out-of-bounds error.
> Fix array out-of-bounds error in test suite.

- Code/components/imgui/ImGuiDriver.cpp
Currently, all cyrillic text in the debug menu is displayed as "??????". The Roboto font used for ImGui, which is [stored as base85 here](https://github.com/tiltedphoques/TiltedEvolution/blob/bd9a756dcce2dfde1199f7bb0b9e65658468b24f/Code/components/imgui/ImguiFont.inl#L3) supports cyrillic glyphs, so why not use it?
> Fix: Support cyrillic text in the ImGui debug menu

- Code/immersive_launcher/oobe/PathSelection.cpp
Adds TARGET_NAME to the executable elements to select from in the executable-select dialog 
Related feature request https://github.com/tiltedphoques/TiltedEvolution/issues/656
> tweak: add TARGET_NAME to selectable-executable filter

- Code/encoding/Structs/ServerSettings.cpp
- Code/encoding/Structs/ServerSettings.h
- Code/server/GameServer.cpp
- Code/server/Services/PartyService.cpp
- Code/server/Services/PartyService.h
If there are no parties on the server, when a party is created, every player is automatically added to the party
If there is one party in the server, when a player connects, they are automatically added to the party
Can be toggled in the server config (on by default)
For issues #378 and #404
> Feature: auto party join

- Code/client/Games/Skyrim/EquipManager.cpp
- Code/client/Services/Generic/InventoryService.cpp
Could potentially fix invisible weapons as well, would have to be tested.
> Fix: don't send queued (un)equip messages

- Code/client/Events/AddTargetEvent.h
- Code/client/Games/Skyrim/Effects/ActiveEffect.h
- Code/client/Games/Skyrim/Magic/MagicTarget.cpp
- Code/client/Games/Skyrim/Projectiles/Projectile.h
- Code/client/Services/Generic/MagicService.cpp
- Code/encoding/Messages/AddTargetRequest.cpp
- Code/encoding/Messages/AddTargetRequest.h
- Code/encoding/Messages/NotifyAddTarget.cpp
- Code/encoding/Messages/NotifyAddTarget.h
- Code/server/Services/MagicService.cpp
It is important to propogate the caster so that the damage handling code can determine whether to cancel the damage event or not.
> fix: spell damage

- Code/client/Games/Skyrim/Forms/MagicItem.cpp
- Code/client/Games/Skyrim/Forms/MagicItem.h
- Code/client/Services/Generic/MagicService.cpp
> fix bound weapon spell

- Code/immersive_launcher/Launcher.cpp
- Code/immersive_launcher/Main.cpp
- Code/immersive_launcher/utils/NvidiaUtil.cpp
- Code/immersive_launcher/utils/NvidiaUtil.h
I should mention that the driver loads nvspcap64.dll regardless of whether you have the overlay enabled or not
> Fix: black screen on nvidia GPUs

- Code/immersive_launcher/Launcher.cpp
- Code/immersive_launcher/Launcher.h
- Code/immersive_launcher/oobe/PathArgument.cpp
- Code/immersive_launcher/oobe/PathArgument.h
Adds the game exe portion of https://github.com/tiltedphoques/TiltedEvolution/issues/627
I am not sure how SKSE wouldn't be loaded if it is installed correctly so I will leave that for a different PR if it is necessary.
ex. 
`SkyrimTogether.exe --exePath C:\Path\To\Game\SkyrimSE.exe`
or
`SkyrimTogether.exe --exePath "C:\Path\With a space\SkyrimSE.exe"`
> Game exe path command line argument

- .github/workflows/linux.yml
- xmake.lua
At some point we'll need to further investigate this:
```
[ 84%] Linking CXX executable crashpad_handler
/usr/bin/ld: ../snapshot/libcrashpad_snapshot.a(system_snapshot_linux.cc.o): in function `crashpad::internal::SystemSnapshotLinux::~SystemSnapshotLinux()':
system_snapshot_linux.cc:(.text+0x2bc): undefined reference to `crashpad::internal::CpuidReader::~CpuidReader()'
/usr/bin/ld: ../snapshot/libcrashpad_snapshot.a(system_snapshot_linux.cc.o): in function `crashpad::internal::SystemSnapshotLinux::SystemSnapshotLinux()':
system_snapshot_linux.cc:(.text+0x620): undefined reference to `crashpad::internal::CpuidReader::CpuidReader()'
/usr/bin/ld: ../snapshot/libcrashpad_snapshot.a(system_snapshot_linux.cc.o): in function `crashpad::internal::SystemSnapshotLinux::CPURevision() const': …
```
> Fix: attempt to temporarily fix failing linux CI

- xmake.lua
Previous commit that changed this line: https://github.com/tiltedphoques/TiltedEvolution/commit/a94f7168666b831a6b0447121307453fc23a05a8#diff-1e65723e47b81d67c25a98980a10861a012068422521d2331e559e547a4e79ccL11
Release .exe now builds just fine and the size is smaller
> Fix: bring back missing 'release' mode to the build config

- Code/client/TiltedOnlineApp.cpp
- Code/server_runner/main.cpp
Change spdlog::set_pattern() to provide more useful logs/tracing for distributed, multithread debugging. 
Adds milliseconds and thread IDs to the logs. 
If you do single-system, multi-clients and server all on the same system, you could actually send all logs to one file and they will be interleaved correctly (mostly). Thread IDs might collide, but not on the same system.
> Better logging for debugging distributed multithreaded apps.

- Code/client/Games/Skyrim/Components/BGSAttackDataForm.h
Assigned here during `TESNPC::Initialize()`
https://github.com/tiltedphoques/TiltedEvolution/blob/20b44d3ca2b1a65b601cd1534ac745eebe9bd859/Code/client/Games/Forms.cpp#L55-L71
^ Notice how `attackDataMap` is taken from the PlayerCharacter singleton and assigned to a remote player's TESNPC. When that TESNPC unloads, the game (supposedly) tries to deallocate its resources, including this map
Changed raw pointer to a `NiPointer` which uses refcount, saving us from the crash
Partially addresses #723 (0x140443C43 crash site)
> Fix cell-change crash caused by use-after-free of BGSAttackDataMap

- Code/client/CrashHandler.cpp
- Code/client/CrashHandler.h
- Code/client/TiltedOnlineApp.h
Enables various crashloggers to work with STR.
CrashHandler is always constructed now, but is IS_MASTER aware and disables minidumps when IS_MASTER is true. Unless you turn the flag back on with a debugger.
> Exception handling fix so SetUnhandledExceptionFilter works

- Code/client/Games/Skyrim/Actor.cpp
- Code/client/Services/Generic/CharacterService.cpp
This fixes a cell change crash provoked by bugs in Actor::SetActorInventory(), but really a bug in the downcall to EquipManager::UnequipAll() which invokes skyrim-native TUnequipAll.
SetActorInventory() effectively calls UnequipAll(), RemoveAllItems(), then sets the new inventory with AddRemoveItem(). But the RemoveAllItems() script _also_ Unequips() each item, which seems to trigger a bug because the UnequipAll is still animating unequips. 
First fix is comment out the unequipall.
Second fix is remove as many SetActorInventory() calls as possible. In particular, when you set the inventory on a local Actor, you don't also have to set it again when the change reflects back to you in OnRemoteSpawnDataReceived(). That's just a more elaborate way of provoking overlapping Unequips (basically, …
> Fix cell-change crash from SetActorInventory() calling s_unequipAll followed by s_removeAllItems

- Code/client/NvidiaUtil.cpp
- Code/client/NvidiaUtil.h
- Code/client/TiltedOnlineApp.cpp
Black screen fix still applies. Dynamic invocation is needed in order not to link `d3d11.dll` at compile-time (compile-time linking breaks ENB and other mods that use d3d11.dll as a proxy)
> Change `D3D11CreateDevice` invocation in NvidiaUtil to a dynamic one

- Code/client/Services/Generic/CharacterService.cpp
The call to retrieve the Actor:: can fail, so avoid the crash.
> Fix crash in OnNotifyRelinquishControl

- Code/client/Services/Generic/ActorValueService.cpp
To fix the issue where the character's maximum value is not properly synchronized.
> fix requestMaxValueChanges

- Code/client/ModCompat/BehaviorVar.cpp
Multiple behavior replacers have the same signature, choosing the first one.
> Fix: Resolve animal sliding issue

- .github/workflows/windows-playable-build.yml
- Added trigger on a tag push (that I completely forgot about in the previous PR)
- Artifact's version string now matches the one in `BuildInfo.h` and in-game
- Attempt at xmake deps caching
@maximegmd @RobbeBryssinck during my research on xmake caching I saw that `actions/cache` didn't stay for long in your repos (including both TiltedEvolution and CyberEngineTweaks) and eventually was commented out/removed. Why? Any pitfalls I'm not aware of?
> CI update: correct artifact versioning, tags trigger, xmake deps caching

- Code/client/Services/Generic/InputService.cpp
Currently, when focusing the window (aka tabbing in) with the UI visible you cannot interact with the UI and must close/reopen to interact with it.
This PR forces the UI state when the WM_SETFOCUS message is sent to InputService to fix the above.
> Fix UI state when focusing window with UI visible

- Code/immersive_launcher/TargetConfig.h
- Code/immersive_launcher/stubs/FileMapping.cpp
This is a compatibility change, works on 23H2 and 24H2. Since in 24H2 GetModuleHandle no longer down-calls to LdrGetDllHandleEx, have to hook the GetModuleHandle() routines also.
> Windows 11 24H2 changed some low-level call hierarchies.

- Code/components/resources/ResourceCollection.cpp
To avoid confusion for users who might attribute a missing `resources` directory as something breaking, create the `resources` directory rather than notifying it's missing.
> Create resources directory if not found

- Code/client/xmake.lua
The DLL was not copied during `xmake install -o distrib`
> Fixed Discord rich presence not working due to a missing dll

- Code/components/console/ConsoleRegistry.cpp
This was previously mentioned in the discord but server console commands should be case-insensitive. 
To preserve their capitalization, I decided against saving commands/settings as all lowercase so the `/help` command would look nicer than many completely lowercase command/setting names.
ex. 
- `/set gameserver:spassword pass`
- `/UPTIME` 
It also adds another expected option to `BoolifyString`.
> Case-insensitive server console commands/settings

- .github/workflows/windows-playable-build.yml
- Code/server_runner/xmake.lua
Removing .pdb wasn't the brightest idea. It's much easier to decipher crash logs from release builds using debug symbols, especially when there's STR on the call stack
> CI: keep debug symbols (.pdb), but upload them as a separate artifact

- Code/client/Services/Generic/ObjectService.cpp
Otherwise the party leader overrides everyone's stuff
(Did a play-test. Works)
> Exclude the equipment chest from sync in "No One Escapes Cidhna Mine"

- Code/client/TiltedOnlineApp.cpp
Closes #92
Closes #448 
Testing assists by @absol89, @miredirex, Vende. None of us have seen any issues, and it fixes things like neck seams and black faces. 
More technical version:
Reverting a change that forced bUseFaceGenPreprocessedHeads=false (the Skyrim default is true). Extensive testing over months by multiple parties showed that enabling the flag introduces no issues _with properly generated characters_ (in-game character generation or showracemenu). The popular testing shortcut of  "coc riverwood" from the main menu skips proper character generation.
Plus, having the flag on has some benefits like helping with neck seams.
The original behavior of the flag is restored, so if any issues do crop up it can be disabled in the [General] section of Skyrimprefs.ini.
~~There are still …
> Revert force bUseFaceGenPreprocessedHeads = false

- .github/workflows/linux.yml
- .github/workflows/windows-playable-build.yml
- .github/workflows/windows.yml
Builds started failing on 2.9.5, sol2 wouldn't compile - likely related to https://github.com/xmake-io/xmake-repo/pull/6251. Also disabled scheduled runs in forks (sorry for the emails :sdwut:)
> CI: bump xmake version, disable cron runs in forks

- Code/skyrim_ui/src/assets/i18n/fr.json
Interface is spelled the same in French, not sure how the "é" and the missing "r" happened there, as it's spelled correctly on the line right under.
> Fixed French Typo

- Code/client/Games/Skyrim/Forms/MagicItem.cpp
- Code/client/Games/Skyrim/Magic/EffectItem.cpp
As the title says. Bethesda bug.
BGSKeywordForm::Contains(pKeywordList) returns true if the keyword list is zero length. This PR checks for the condition and returns false.
There are only 4 places in STR that invoke this function, so I took the simple approach of just fixing them rather than the more-invasive wrapper class to fix it.
I left in the logging to find places that are triggering the bug, but they are at ::debug level. 
The places this will happen is when a Magic item, effect, Health item/effect has no keywords defined on the relevant formID. That probably is never supposed to happen, but it does.
> Guard against BGSKeywordForm::Contains() bug, which returns true when there are zero keywords

- Code/client/Games/Skyrim/Actor.cpp
This PR corrects the setting of actor property values, primarily addressing issues that occur during ownership transfers.
> Fix Incorrect Actor Property Values

- Code/client/Games/ActorExtension.h
- Code/client/Games/Animation.cpp
- Code/client/Services/Generic/CharacterService.cpp
This Pull Request addresses an issue where summoned creatures, such as Daedric Princes, were missing their local weapon equip animations upon summoning during combat.
> Fix missing weapon equip animation

- Code/client/Games/Skyrim/Forms/MagicItem.cpp
- Code/client/Games/Skyrim/Magic/EffectItem.cpp
Update to the previous version of this PR. It is functionally identical, the code is just less ugly.
@Force67, I updated the code because ugly bothers me. Then I saw you had already speedily merged the prior version, so thank you for that. I'm submitting this as a PR because a) I already updated the branch, so why not; and b) so you can choose to merge or ignore as you like.
> Update: Guard against BGSKewordForm::Contains() bug, which returns true when there are zero keywords

- Code/client/Games/Skyrim/Combat/CombatController.h
- Code/client/Services/Debug/Views/CombatView.cpp
This probably never caused any bugs or crashes, but I thought I'd rather update this now than get shot in the foot in the future.
> Use NiPointer instead of raw pointers in CombatController

- Code/client/Services/Generic/CharacterService.cpp
- Code/client/Services/Generic/MagicService.cpp
- Code/client/Services/MagicService.h
(log messages that repeat forever).
For discussion. Would never propose merging such ugly hacks.
> Proof-of-concept work to identify & fix sources of logging loops

- Code/client/Services/Generic/CharacterService.cpp
This PR fixes an issue where disabled actors could not be properly enabled.
﻿
Previously, `pActor->Enable()` was used, but it did not correctly activate disabled actors.  
By replacing it with `pActor->EnableImpl()`, the actor is now properly enabled and becomes active in the world.
> Fix actor enable issue by using EnableImpl

- Code/client/Games/Primitives.h
- Code/client/Games/Skyrim/Forms/MagicItem.cpp
Spells themselves typically don't have keywords, which are on their effects.
As a result, returning false if the spell has no keywords leads to the check returning false incorrectly.
Something of note: while the actual use of the checks is unchanged, this actually breaks certain spell VFX which no longer show on remote clients because the spell cast is not replicated for them. This is simply a result of the intended behavior. To sync spell VFX (for example, on self-healing) without replicating the actual spell cast itself, more work is needed.
> Fix certain spell type checks that did not check for keywords on effects

- Code/client/Games/Skyrim/Forms/TESQuest.cpp
This started as a bug hunt for misc. quest syncing, but it effects ALL quest type progression. When the quest stage is set, syncing will cause each player to try to set it, which can cause duplication of steps or unwanted progression.
The fix is to make sure desired quest stage != current quest stage.
> Prevent multiple triggers of quest stage change

- Code/client/Services/Debug/DebugService.cpp
- Code/client/Services/DebugService.h
- Code/client/Systems/RenderSystemD3D11.cpp
I honestly don’t understand how you managed without this for so many years https://imgur.com/a/0IfKGut. The function is a no-op in nexus (master branch) builds
> Improve dev experience: arrange secondary game window

- Code/client/Games/Skyrim/Forms/MagicItem.cpp
At long last, here is the real, supportable, always-works version of  the Bow of Shadows invisibility sync fix.
Credit to @miredirex for pointing me in the right direction for dealing with shifting mod IDs / formIDs so it will always work.
Deals with the one special case that BoS needs to be exempted from PR #796. If we find more it needs an array of baseFormIds and mod string structures and a loop to handle them all, but the pattern should be good.
> Fix PR #796, needs exception for Bow of Shadows.
